name: Build Dylib
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare Theos
        run: |
          export THEOS=~/theos
          git clone --recursive https://github.com/theos/theos.git $THEOS
          curl -LO https://github.com/theos/sdks/archive/master.zip
          unzip master.zip
          mv sdks-master/*.sdk $THEOS/sdks
          rm -rf sdks-master master.zip

      - name: Build Package
        run: |
          export THEOS=~/theos
          make package FINALPACKAGE=1

      - name: Upload Dylib
        uses: actions/upload-artifact@v3
        with:
          name: AuthSystem-Dylib
          path: .theos/obj/debug/AuthSystem.dylib
